version: '3.8'

services:

  nextjs-app:
    image: node:latest
    container_name: next
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "8811:3000"
    command: npm run dev
    # in IIS on super machine, this is reverse proxied.

  mongodb:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"

#   command: npm install -y

